<a href="https://colab.research.google.com/github/moin070/Internship/blob/main/task_5/Linear_Regressioni_pynb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
df=pd.read_csv("/content/drive/MyDrive/Advertising.csv")
df.head()

Unnamed: 0     TV  Radio  Newspaper  Sales
0           1  230.1   37.8       69.2   22.1
1           2   44.5   39.3       45.1   10.4
2           3   17.2   45.9       69.3    9.3
3           4  151.5   41.3       58.5   18.5
4           5  180.8   10.8       58.4   12.9

In [4]:
#preprocessing the data
df.isnull().sum()
df.dropna()

Unnamed: 0     TV  Radio  Newspaper  Sales
0             1  230.1   37.8       69.2   22.1
1             2   44.5   39.3       45.1   10.4
2             3   17.2   45.9       69.3    9.3
3             4  151.5   41.3       58.5   18.5
4             5  180.8   10.8       58.4   12.9
..          ...    ...    ...        ...    ...
195         196   38.2    3.7       13.8    7.6
196         197   94.2    4.9        8.1    9.7
197         198  177.0    9.3        6.4   12.8
198         199  283.6   42.0       66.2   25.5
199         200  232.1    8.6        8.7   13.4

[200 rows x 5 columns]

In [ ]:
#here we give values to x variable
x=df.iloc[:,0:-1].values
x

In [ ]:
#here we give values to y variable
y=df.iloc[:,1].values
y

In [11]:
# Now spliting the dtaa into training and testing sets
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=42)

In [12]:
x_test

array([[ 96. , 163.3,  31.6,  52.9],
       [ 16. , 195.4,  47.7,  52.9],
       [ 31. , 292.9,  28.3,  43.2],
       [159. ,  11.7,  36.9,  45.2],
       [129. , 220.3,  49. ,   3.2],
       [116. ,  75.1,  35. ,  52.7],
       [ 70. , 216.8,  43.9,  27.2],
       [171. ,  50. ,  11.6,  18.4],
       [175. , 222.4,   3.4,  13.1],
       [ 46. , 175.1,  22.5,  31.5],
       [ 67. ,  31.5,  24.6,   2.2],
       [183. ,  56.2,   5.7,  29.7],
       [166. , 234.5,   3.4,  84.8],
       [ 79. ,   5.4,  29.9,   9.4],
       [187. , 139.5,   2.1,  26.6],
       [178. , 170.2,   7.8,  35.2],
       [ 57. ,   7.3,  28.1,  41.4],
       [153. , 197.6,  23.3,  14.2],
       [ 83. ,  75.3,  20.3,  32.5],
       [ 69. , 237.4,  27.5,  11. ],
       [125. , 229.5,  32.3,  74.2],
       [ 17. ,  67.8,  36.6, 114. ],
       [149. ,  38. ,  40.3,  11.9],
       [ 94. , 250.9,  36.5,  72.3],
       [ 66. ,  69. ,   9.3,   0.9],
       [ 61. ,  53.5,   2. ,  21.4],
       [ 85. , 213.5,  43. ,  33.8],
 

In [14]:
y_train

array([284.3, 184.9, 112.9,  23.8, 290.7,  19.4, 293.6,  18.7, 134.3,
        25.6, 100.4,  80.2, 188.4, 177. , 125.7, 209.6, 142.9, 184.9,
       222.4, 241.7,  17.2, 120.5,  89.7, 191.1,  75.5, 193.2,  85.7,
       266.9,  39.5, 261.3,  13.2, 193.7, 296.4, 265.6, 214.7, 149.7,
       131.7,  57.5, 240.1, 141.3, 180.8,  97.2, 220.5, 140.3, 255.4,
        96.2,  66.1, 239.3, 175.7, 240.1,  17.9, 230.1, 283.6, 171.3,
       199.1, 123.1, 131.1,  25.1, 163.5, 248.8, 202.5,  13.1,   4.1,
        93.9, 262.9, 228.3, 253.8, 243.2, 239.8, 228. , 215.4, 239.9,
       107.4, 187.8, 206.9,  43. , 151.5, 137.9, 182.6, 219.8, 156.6,
       276.7, 205. ,  66.9,  76.4,  95.7, 120.2, 225.8,  28.6,  68.4,
       248.4, 218.5, 109.8,   8.6,  97.5, 210.7, 164.5, 265.2, 281.4,
        26.8, 276.9,  36.9, 206.8, 287.6, 102.7, 262.7,  90.4, 199.8,
        94.2, 210.8, 227.2,  88.3, 237.4, 136.2, 172.5,  17.2,  59.6,
        74.7, 149.8, 166.8,  44.5, 216.4,  44.7,   0.7, 121. , 187.9,
       135.2, 139.2,

In [16]:
#now linear regression of the advertising data
from sklearn.linear_model import LinearRegression
dfg=LinearRegression()
dfg

LinearRegression()

In [26]:
dfg.fit(x_train,y_train)
#prediction values of x test
y_predict=dfg.predict(x_test)
y_predict

array([163.3, 195.4, 292.9,  11.7, 220.3,  75.1, 216.8,  50. , 222.4,
       175.1,  31.5,  56.2, 234.5,   5.4, 139.5, 170.2,   7.3, 197.6,
        75.3, 237.4, 229.5,  67.8,  38. , 250.9,  69. ,  53.5, 213.5,
       139.3,  87.2,   8.4, 199.8,  69.2, 198.9,  16.9, 280.7, 238.2,
        48.3, 273.7, 117.2,  27.5, 116. , 177. ,  43.1,  62.3, 224. ,
        38.2,  70.6, 147.3, 104.6,  76.3,  78.2, 168.4,   8.7,   7.8,
        76.4, 129.4,  73.4, 289.7,  19.6, 197.6])

In [27]:
y_test

array([163.3, 195.4, 292.9,  11.7, 220.3,  75.1, 216.8,  50. , 222.4,
       175.1,  31.5,  56.2, 234.5,   5.4, 139.5, 170.2,   7.3, 197.6,
        75.3, 237.4, 229.5,  67.8,  38. , 250.9,  69. ,  53.5, 213.5,
       139.3,  87.2,   8.4, 199.8,  69.2, 198.9,  16.9, 280.7, 238.2,
        48.3, 273.7, 117.2,  27.5, 116. , 177. ,  43.1,  62.3, 224. ,
        38.2,  70.6, 147.3, 104.6,  76.3,  78.2, 168.4,   8.7,   7.8,
        76.4, 129.4,  73.4, 289.7,  19.6, 197.6])

In [30]:
#Evaluate the mean square error of testing sets
from sklearn.metrics import mean_squared_error, r2_score
import numpy as np
y_pred = dfg.predict(x_test)
np.sqrt(mean_squared_error(y_test, y_pred))
     

4.7531792909477655e-14

In [31]:
# Now we calculatin the R-squared
r_squared = r2_score(y_test, y_pred)
r_squared

1.0

In [36]:
#prediction for new product
dfgh =  np.array([[5000, 30, 20, 10], [6000, 40, 30, 20], [7000, 50, 40, 30]])
new_sales = dfg.predict(dfgh)
new_sales

array([30., 40., 50.])